# Generated by Django 6.0 on 2025-12-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_produto_criado_em_carrinho_estoque_itemcarrinho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_destinatario',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do destinatário'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_rua',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto Bancário')], max_length=20, verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
    ]
