# Generated by Django 5.2.6 on 2025-12-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_pedido_endereco_bairro_pedido_endereco_cep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
        migrations.AlterModelOptions(
            name='imagemproduto',
            options={'verbose_name': 'Imagem do Produto', 'verbose_name_plural': 'Imagens dos Produtos'},
        ),
        migrations.AlterModelOptions(
            name='itemcarrinho',
            options={'verbose_name': 'Item do Carrinho', 'verbose_name_plural': 'Itens do Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens dos Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
